import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 32, padding: '24px 0 12px 0', background: 'rgba(0,0,0,0.04)', fontWeight: 600, fontSize: 18 }}>
          <a href="/" style={{ textDecoration: 'none', color: '#7f5af0' }}>Home</a>
          <a href="/contact" style={{ textDecoration: 'none', color: '#7f5af0' }}>Contact</a>
          <a href="/terms" style={{ textDecoration: 'none', color: '#7f5af0' }}>Terms</a>
          <a href="/privacy" style={{ textDecoration: 'none', color: '#7f5af0' }}>Privacy</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
